server:
  port: 8080

spring:
  jackson:
    serialization:
      indent_output: true

  # JWT configuration
  jwt:
    secret: my_secret_key_for_jwt_singing # use a long and strong one in production
    expiration: 3600000  # 1 hour in milliseconds

  # Logging
  logging:
    level:
      org.springframework: INFO
      com.bacExam: DEBUG

  # (optional) CORS _ in case you're connecting to frontend later
  cors:
    allowed-origins: http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: "*"

## Datasource for h2
  datasource:
    url: jdbc:h2:mem:school_db
    username: root
    password: toor
    driver-class-name: org.h2.Driver

  # database configuration
  h2:
    console:
      enabled: true
      path: /h2-console # access it at http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: update # use 'create' or 'create-drop' for full reset during dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect


########################### PRODUCTION CODE ##############################

## Datasource for postgreSQL
#  datasource:
#    url: jdbc:postgresql://localhost:5432/school_db
#    username: root
#    password: toor
#    driver-class-name: org.postfresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update # Change to 'validate' or 'none' in production
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect